apiVersion: v1
kind: Service
metadata:
  name: foxbit-api-calc-service
  namespace: default
spec:
  selector:
    app: foxbit-api-calc
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000